apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany  
  resources:
    requests:
      storage: 20Gi
